import './globals.css';
import Navbar from '../components/Navbar';
import Form from '../components/Form';
export const metadata = {
  title: 'Resto App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Form />
        {children}
      </body>
    </html>
  );
}
